apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  activeDeadlineSeconds: 300
  template:
    name: db-migrate
    spec:
      restartPolicy: Never
      containers:
        - name: db-migrate
          {{- $repo := required "containerImage.repository is required" .Values.containerImage.repository }}
          {{- $tag := required "containerImage.tag is required" .Values.containerImage.tag }}
          image: "{{ $repo }}:{{ $tag }}"
          command:
            - bundle
            - exec
            - rails
            - db:migrate:primary
          {{- /* START ENV VAR LOGIC */ -}}
          {{- if index $hasInjectionTypes "hasEnvVars" }}
          env:
          {{- end }}
          {{- range $key, $value := .Values.envVars }}
          - name: {{ $key }}
            value: {{ quote $value }}
          {{- end }}