{{- /*
The main Deployment Controller for the application being deployed. This resource manages the creation and replacement
of the Pods backing your application.
*/ -}}
{{ include "k8s-service.deploymentSpec" (dict "Values" .Values "isCanary" false "Release" .Release "Chart" .Chart) }}
